name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # skip Checkstyle for now, update later.
      # - name: Lint with Checkstyle
      #  run: mvn checkstyle:check

      - name: Run tests
        run: mvn test

      - name: Build with Maven
        run: mvn clean package -DskipTests